backend:
  name: github
  repo: MikeMcDonald83/PKCETESTING
  branch: main
  base_url: https://sveltia-cms-auth.mikemcdonald83.workers.dev
collections:
  - label: "Blog"
    name: "blog"
    folder: "_posts/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
media_folder: "_media"